components:
  - alignment
  - floats
  - grid
  - hyphenation
  - interactions
  - lists
  - media-objects
  - position
  - scrollable
  - sizing
  - spacing
  - text
  - themes
  - truncation
  - visibility
