components:
  - accordion
  - activity-timeline
  - app-launcher
  - badges
  - breadcrumbs
  - buttons
  - button-icons
  - button-groups
  - cards
  - data-tables
  - datepickers
  - docked-composer
  - docked-utility-bar
  - dynamic-icons
  - feeds
  - files
  - file-selector
  - forms
  - global-header
  - global-navigation
  - icons
  - images
  - list-builder
  - lookups
  - menus
  - modals
  - navigation
  - notifications
  - page-headers
  - panels
  - picklist
  - pills
  - process
  - progress-bar
  - progress-indicator
  - popovers
  - publishers
  - rich-text-editor
  - spinners
  - tabs
  - tiles
  - tooltips
  - trees
  - walkthrough
