components:
  - activity-timeline
  - badges
  - breadcrumbs
  - buttons
  - button-groups
  - cards
  - comments
  - data-tables
  - datepickers
  - dropdowns
  - feeds
  - forms
  - grid-system
  - icons
  - images
  - lookups
  - media-objects
  - modals
  - notifications
  - page-headers
  - picklists
  - pills
  - popovers
  - publishers
  - spinners
  - tabs
  - tiles
  - tooltips
  - trees
