components:
  - activity-timeline
  - app-launcher
  - badges
  - breadcrumbs
  - buttons
  - button-groups
  - cards
  - data-tables
  - datepickers
  - docked-composer
  - docked-utility-bar
  - feeds
  - forms
  - global-header
  - global-navigation
  - grid-system
  - icons
  - images
  - list-builder
  - lookups
  - media-objects
  - menus
  - modals
  - navigation
  - notifications
  - page-headers
  - panels
  - pills
  - process
  - popovers
  - publishers
  - spinners
  - tabs
  - tiles
  - trees
