components:
  - activity-timeline
  - badges
  - breadcrumbs
  - buttons
  - button-groups
  - cards
  - data-tables
  - datepickers
  - docked-composer
  - feeds
  - forms
  - icons
  - images
  - lookups
  - menus
  - modals
  - navigation
  - notifications
  - page-headers
  - panels
  - pills
  - process
  - product-selector
  - popovers
  - publishers
  - spinners
  - tabs
  - tiles
  - trees
