language: node_js
node_js:
  - "4.2"
before_install:
  - rvm install 2.2.2
  - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
install:
  - bundle install --path vendor/bundle
  - npm install
script:
  - scripts/travis/script.sh
cache:
  directories:
    - node_modules
    - vendor/bundle
