status: 'dev-ready'
classBase: 'card'
flavors:
  - base
  - base-narrow
  - related-list-with-tiles
  - related-list-with-table
  - related-list-narrow
lightning:
  namespace: lightning:card
  url: https://developer.salesforce.com/docs/atlas.en-us.204.0.lightning.meta/lightning/aura_compref_lightning_card.htm
