status: 'dev-ready'
classBase: 'badge'
flavors:
  - base
lightning:
  namespace: lightning:badge
  url: https://developer.salesforce.com/docs/atlas.en-us.204.0.lightning.meta/lightning/aura_compref_lightning_badge.htm
