classBase: 'dropdown'
status: 'dev-ready'
flavors:
  - dropdown
  - dropdown-positioning
  - picklist
  - picklist-multi-select
  - search-overflow
  - action-overflow
  - action-overflow-for-touch
dependencies:
  - helpers/text
  - core/icons
