status: 'dev-ready'
flavors:
  - colors
  - sizes
  - containers
lightning:
  namespace: lightning:spinner
  url: https://developer.salesforce.com/docs/atlas.en-us.204.0.lightning.meta/lightning/aura_compref_lightning_spinner.htm
