status: 'dev-ready'
className: 'textarea'
lightning:
  namespace: lightning:textarea
  url: https://developer.salesforce.com/docs/atlas.en-us.204.0.lightning.meta/lightning/aura_compref_lightning_textarea.htm
