status: 'dev-ready'
flavors:
  - base
  - sub-tabs
lightning:
  namespace: lightning:tabset
  url: https://developer.salesforce.com/docs/atlas.en-us.206.0.lightning.meta/lightning/aura_compref_lightning_tabset.htm
