status: 'dev-ready'
classBase: 'button'
flavors:
  - base
  - stateful
  # - icon
  - icon-size
  - icon-container
  - icon-container-size
  - icon-with-hint-hover
  - icon-with-dropdown
lightning:
  namespace: lightning:buttonIcon
  url: https://developer.salesforce.com/docs/atlas.en-us.204.0.lightning.meta/lightning/aura_compref_lightning_buttonIcon.htm
